name: Ibrahim Malik
bio: A passionate baseball fan trying to speak assembly fluently

external-image: false
picture: assets/images/profile2.jpg
picture3: assets/images/chi.jpg

url: http://ibhm.github.io


permalink: /:title/

# if you don't have any of social below, comment the line
facebook: ibrahimhasanmalik
# twitter: mytwitter
# google: mygoogle
instagram: ibrahimhmalik
# pinterest: mypinterest
linkedin: ibrahimhmalik
# youtube: myyoutube
# spotify: myspotify
github: ibhm
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: ibhm@live.com

authors:
    johndoe:
        name: Ibrahim Malik
        bio: A passionate baseball fan trying to speak assembly fluently
        external-image: false
        picture: assets/images/profile2.jpg

width: large


# if you don't need "about" or "blog", comment them out below
about: true


# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

baseurl: "ibhm.github.io"
